### ISSUE TITLE
v11.1 CONFIG can't save and load

### ISSUE THREAD

**Issue by WonderAndroid324** [YDC-Deadly/NG-injector#10]
i tried to save the config but it can't be load when inject 
and i cant find config .txt or .h file in RoamingState

**Comment by adgods1** [comment]
that is a you problem

**Comment by WonderAndroid324** [comment]
> that is a you problem

Do you test？😥

**Comment by haxjp** [comment]
> 構成を保存しようとしましたが、インジェクト時にロードできず 、RoamingStateで構成.txtまたは.hファイルが見つかりません
RoamingState/NGClient/Configs/NGClient.txt
